### ISSUE TITLE
zero3预训练相关问题

### ISSUE THREAD

**Issue by wang99711123** [CVI-SZU/Linly#61]
您好，我尝试llama7B的预训练 使用了zero3 遇到了一个报错

我的命令如下，几乎与您的示例相同

```shell
deepspeed --hostfile=hostfile --master_addr=$ip pretrain.py --deepspeed --deepspeed_config models/deepspeed_zero3_config.json --enable_zero3\
                      --pretrained_model_path models/llama/llama-7b.bin \
                      --dataset_path $data_path --spm_model_path llama-7b-hf/tokenizer.model \
                      --config_path models/llama/7b_config.json \
                      --output_model_path llama/output_model.bin \
                      --deepspeed_checkpoint_activations \
                      --world_size 16 --learning_rate 1e-4 \
                      --data_processor lm --total_steps 10000 --save_checkpoint_steps 20 --batch_size 1
``` 
部分报错信息如下

```shell
Traceback (most recent call last):
  File "pretrain.py", line 134, in <module>
    main()
  File "pretrain.py", line 130, in main
    trainer.train_and_validate(args)
  File "/workspace/raid/HOME/TencentPretrain/tencentpretrain/trainer.py", line 49, in train_and_validate
    model_for_training = _load_state_dict_into_model(model_for_training, args.lora_pretrained_model_path, "")
  File "/workspace/raid/HOME/TencentPretrain/tencentpretrain/model_loader.py", line 23, in _load_state_dict_into_model
    state_dict = torch.load(model_path, map_location="cpu")
  File "/opt/conda/envs/pretrain/lib/python3.8/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/conda/envs/pretrain/lib/python3.8/site-packages/torch/serialization.py", line 276, in _open_file_like
    return _open_buffer_reader(name_or_buffer)
  File "/opt/conda/envs/pretrain/lib/python3.8/site-packages/torch/serialization.py", line 261, in __init__
    _check_seekable(buffer)
  File "/opt/conda/envs/pretrain/lib/python3.8/site-packages/torch/serialization.py", line 357, in _check_seekable
    raise_err_msg(["seek", "tell"], e)
  File "/opt/conda/envs/pretrain/lib/python3.8/site-packages/torch/serialization.py", line 350, in raise_err_msg
    raise type(e)(msg)
AttributeError: 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.
``` 
请问这是什么原因呢

**Comment by fengyh3** [comment]
tencentpretrain/utils/constants.py的第四行改为with open("models/llama_special_tokens_map.json", mode="r", encoding="utf-8") as f:

**Comment by wang99711123** [comment]
这个已经改过了，我觉得不是这个原因，感谢您的帮助
我将/workspace/raid/HOME/TencentPretrain/tencentpretrain/trainer.py 的第49行注释掉了，虽然程序可以跑通了，但是不知道会不会有什么影响？

> tencentpretrain/utils/constants.py的第四行改为with open("models/llama_special_tokens_map.json", mode="r", encoding="utf-8") as f: 试试？

**Comment by wang99711123** [comment]
@ydli-ai 大佬能帮忙看下嘛
