### ISSUE TITLE
运行llama-7b微服务时，报错

### ISSUE THREAD

**Issue by heiheiwangergou** [CVI-SZU/Linly#76]
WechatIMG126.png

**Comment by heiheiwangergou** [comment]
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /root/miniconda3/envs/linly_llama/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/root/miniconda3/envs/linly_llama/lib/python3.8/site-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
CUDA SETUP: Loading binary /root/miniconda3/envs/linly_llama/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
Traceback (most recent call last):
  File "llama_server.py", line 86, in <module>
    init_model()
  File "llama_server.py", line 45, in init_model
    args.tokenizer = Tokenizer(model_path=args.spm_model_path)
  File "/data/lihu/llama_inference/model/tokenize.py", line 16, in __init__
    assert os.path.isfile(model_path), model_path
AssertionError: ./root/lihu/ChatFlow-7B/tokenizer.model

**Comment by fengyh3** [comment]
可以提供更多的信息吗？例如你启动脚本是什么？
